# Anaconda profile for Ultramarine Linux Budgie

[Profile]
# Define the profile.
profile_id = ultramarine-budgie
base_profile = ultramarine

[Profile Detection]
# Match os-release values.
os_id = ultramarine
variant_id = budgie

[Payload]
default_environment = ultramarine-budgie-product-environment

[Bootloader]
menu_auto_hide = True

[User Interface]
hidden_spokes =
    NetworkSpoke
    PasswordSpoke
    UserSpoke
