name: Update
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:frawhide
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}

      - name: Install SSH signing key & Set up git repository
        run: |
          mkdir -p ${{ runner.temp }}
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ${{ runner.temp }}/signing_key
          chmod 0700 ${{ runner.temp }}/signing_key
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run Update
        run: anda update -vv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full

      - name: Save
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "Raboneko"
            git config user.email "raboneko@fyralabs.com"
            git config gpg.format "ssh"
            git config user.signingkey "${{ runner.temp }}/signing_key"
            msg="bump: $(git status | grep modified | sed -r 's@.+/([^/]+)/[^/]+\n?@\1 @g' | tr -d '\n')"
            git commit -S -a -m "$msg"
            copy_over () {
              git format-patch HEAD^
              git checkout $1
              git apply *.patch || true
              rm *.patch
              git add *
              git commit -S -a -m "$msg"
            }
            copy_over um39 || true
            copy_over um40 || true
            git push -u origin --all
          fi
