name: Push comps updates

on:
  push:
    branches:
      - um41
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f41
    steps:
      - uses: actions/checkout@v4
      - name: Push to subatomic
        run: |
          branch=${{ github.ref_name }}
          ver=${branch/um/}
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            "um${ver}" comps.xml
